Add devise
ANTOINE1128/Blog-App1 pull request #12
Opened 2023-11-08 14:06 UTC by ANTOINE1128

### Project requirements
- Remove `current_user` method in `ApplicationController`, devise will provide us with one.
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

2023-11-08 15:34 UTC, Olamarx requested changes
Hi @tan12082001, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Devise view renders ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 15:34 UTC, Olamarx commented on app/models/user.rb
>    has_many :posts, foreign_key: 'author_id'
- [x] I will strongly advise you to make the confirmable part of it because according to the requirement, the app should ask for email confirmation 
![image](https://github.com/ANTOINE1128/Blog-App1/assets/86200356/996ee835-03eb-4bd2-9a28-1466c74e723d)

2023-11-08 15:34 UTC, Olamarx commented on app/views/devise/registrations/new.html.erb
> +      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
- [ ] I get an error when I want to create an account and this is despite filling the name input as you can see in the attached image. So I could not confirm others such as the reset password fro the recoverable.
![image](https://github.com/ANTOINE1128/Blog-App1/assets/86200356/a2819093-9702-4357-8336-ba2e8bdb329d)

2023-11-09 07:49 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @ANTOINE1128 & @tan12082001, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="300px" />

## Highlights :heavy_check_mark: 
- [x] User authentication  works as expected :white_check_mark: 
- [x] Password reset and email confirmation work correctly :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:    
- [x] Implemented all the changes from the previous reviewer :white_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 09:36 UTC, merged